name: 'Setup'
description: 'Common setup for Node.js and pnpm'
runs:
  using: 'composite'
  steps:
    - uses: jdx/mise-action@v3
      with:
        version: 2025.11.4
        cache: true
    - run: pnpm install
      shell: bash
